# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test-Python:

    strategy:
      matrix:
        python: ["3.7","3.8","3.9","3.10","3.11","3.12","3.13"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python - ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}

    - name: Run Test - ${{matrix.python}}
      run: python test_TemplateStr.py
